package tools.mo3ta.salo.analytics

object AppAnalytics {
    const val MOHAMED_LOVERS_SKY_TAP = "mohamed_lovers_sky_tap"
    const val TAKBEER_ANNOUNCEMENT_OPENED = "takbeer_announcement_opened"
    const val TAKBEER_ANNOUNCEMENT_DISMISSED = "takbeer_announcement_dismissed"
    const val FIRST_OPEN_TOOLTIPS_SHOWN = "first_open_tooltips_shown"
    const val OPEN_INFO_SHEET = "open_info_sheet"
    const val OPEN_MANUAL_SALAWAT = "open_manual_salawat"
    const val OPEN_SETTINGS = "open_settings"
    const val OPEN_TAKBEER_SESSION = "open_takbeer_session"
    const val OPEN_DHIKR_REWARDS = "open_dhikr_rewards"
    const val OPEN_MANUAL_DHIKR = "open_manual_dhikr"
    const val DHIKR_TAP = "dhikr_tap"
    const val DHIKR_SCREEN_VIEW = "dhikr_screen_view"
    const val OPEN_BAQIYAT_CHALLENGE = "open_baqiyat_challenge"
    const val BAQIYAT_SCREEN_VIEW = "baqiyat_screen_view"
    const val BAQIYAT_PHRASE_TAP = "baqiyat_phrase_tap"
    const val BAQIYAT_CYCLE_COMPLETE = "baqiyat_cycle_complete"
    const val OPEN_MANUAL_BAQIYAT = "open_manual_baqiyat"
    const val OPEN_ISTIGHFAR_CHALLENGE = "open_istighfar_challenge"
    const val OPEN_MANUAL_ISTIGHFAR = "open_manual_istighfar"
    const val ISTIGHFAR_TAP = "istighfar_tap"
    const val ISTIGHFAR_SCREEN_VIEW = "istighfar_screen_view"

    const val OPEN_ZABAD_CHALLENGE = "open_zabad_challenge"
    const val OPEN_MANUAL_ZABAD = "open_manual_zabad"
    const val ZABAD_TAP = "zabad_tap"
    const val ZABAD_SCREEN_VIEW = "zabad_screen_view"

    const val OPEN_QURAN_CHALLENGE = "open_quran_challenge"
    const val OPEN_MANUAL_QURAN = "open_manual_quran"
    const val QURAN_TAP = "quran_tap"
    const val QURAN_SCREEN_VIEW = "quran_screen_view"

    const val OPEN_ALBAQARA_CHALLENGE = "open_albaqara_challenge"
    const val ALBAQARA_TAP = "albaqara_tap"
    const val ALBAQARA_SCREEN_VIEW = "albaqara_screen_view"

    const val OPEN_GHARS_CHALLENGE = "open_ghars_challenge"
    const val GHARS_TAP = "ghars_tap"
    const val GHARS_SCREEN_VIEW = "ghars_screen_view"
    const val OPEN_GHARS_GARDENS = "open_ghars_gardens"
    const val OPEN_GHARS_GARDEN = "open_ghars_garden"

    const val OPEN_ALF_HASANA_CHALLENGE = "open_alf_hasana_challenge"
    const val OPEN_MANUAL_ALF_HASANA = "open_manual_alf_hasana"
    const val ALF_HASANA_TAP = "alf_hasana_tap"
    const val ALF_HASANA_SCREEN_VIEW = "alf_hasana_screen_view"

    const val PARAM_COUNT = "count"
    const val LANGUAGE_CHANGED = "language_changed"
    const val SALAWAT_VARIANT_CHANGED = "salawat_variant_changed"
    const val TAKBEER_SESSION_START = "takbeer_session_start"
    const val TAKBEER_USER_DONE = "takbeer_user_done"
    const val TAKBEER_SESSION_STOP = "takbeer_session_stop"
    const val LEADERBOARD_USER_CLICK = "leaderboard_user_click"
    const val NICKNAME_ANNOUNCEMENT_OPENED = "nickname_announcement_opened"
    const val NICKNAME_ANNOUNCEMENT_DISMISSED = "nickname_announcement_dismissed"
    const val SALAWAT_VARIANT_ANNOUNCEMENT_OPENED = "salawat_variant_announcement_opened"
    const val SALAWAT_VARIANT_ANNOUNCEMENT_DISMISSED = "salawat_variant_announcement_dismissed"
    const val REFERRAL_ANNOUNCEMENT_OPENED = "referral_announcement_opened"
    const val REFERRAL_ANNOUNCEMENT_DISMISSED = "referral_announcement_dismissed"
    const val STREAK_BADGE_ANNOUNCEMENT_OPENED = "streak_badge_announcement_opened"
    const val STREAK_BADGE_ANNOUNCEMENT_DISMISSED = "streak_badge_announcement_dismissed"
    const val REVIEW_DIALOG_SHOWN = "review_dialog_shown"
    const val REVIEW_DIALOG_GO_TO_STORE = "review_dialog_go_to_store"
    const val REVIEW_DIALOG_DISMISSED = "review_dialog_dismissed"

    const val PARAM_SOURCE = "source"
    const val PARAM_LANG = "lang"
    const val PARAM_VARIANT = "variant"
    const val PARAM_PEOPLE = "people"
    const val PARAM_ROUND = "round"
    const val PARAM_ROUNDS_COMPLETED = "rounds_completed"
}
